apiVersion: v2
appVersion: 0.7.0
description: OpenEO by TiTiler
name: titiler-openeo
version: 0.12.6
icon: https://raw.githubusercontent.com/developmentseed/titiler/main/docs/logos/TiTiler_logo_small.png
maintainers:
  - name: DevelopmentSeed
    url: https://github.com/developmentseed

dependencies:
  - name: postgresql
    alias: postgresql
    version: "16.6.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
