apiVersion: v2
appVersion: 0.10.1
description: OpenEO by TiTiler
name: titiler-openeo
version: 1.0.0
icon: >-
  https://raw.githubusercontent.com/developmentseed/titiler/main/docs/logos/TiTiler_logo_small.png
maintainers:
  - name: DevelopmentSeed
    url: https://github.com/developmentseed
dependencies:
  - name: postgresql
    alias: postgresql
    version: 16.6.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
